import Head from "next/head";
import { Navbar } from "@/components/Navbar";
import { Presentation } from "@/components/Presentation";
import Cards from "@/components/Cards";
import { collection, getDocs, queryEqual } from "firebase/firestore";
import { db } from "../../firebase/firebaseConfig";
import { GetServerSideProps } from "next";
import { useState } from "react";
export default function Home({ dataPresentation, dataCards }) {
  const presentation = dataPresentation[0];

  return (
    <>
      <Head>
        <title>Othmane Ait Salah - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        />
      </Head>
      <Navbar />
      <main>
        <Presentation
          presentation={presentation.objective}
          name={presentation.name}
          company={presentation.company}
          job={presentation.job}
          description={presentation.description}
          dataCards={dataCards}
        />
      </main>
    </>
  );
}
export const getServerSideProps: GetServerSideProps = async () => {
  const querySnapshotPresentation = await getDocs(
    collection(db, "presentation")
  );
  const dataPresentation = querySnapshotPresentation.docs.map((doc) =>
    doc.data()
  );
  const querySnapshotCards = await getDocs(collection(db, "cards"));
  const dataCards = querySnapshotCards.docs.map((doc) => doc.data());
  return { props: { dataPresentation, dataCards } };
};
