import Head from "next/head";
import { Navbar } from "@/components/Navbar";
import { Presentation } from "@/components/Presentation";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../firebase/firebaseConfig";
import { GetServerSideProps } from "next";
import Form from "@/components/Form";
import { Map } from "@/components/Map";
import { Footer } from "@/components/Footer";

interface DataPresentation {
  company: string;
  description: string[];
  job: string;
  name: string;
  objective: string;
}
interface CardData {
  Oclock: string[];
  Simplon: string[];
  ouivalo: string[];
  unitix: string[];
}
export default function Home({
  formattedDataPresentation,
  formattedDataCards,
}: {
  formattedDataPresentation: DataPresentation;
  formattedDataCards: CardData;
}) {
  return (
    <>
      <Head>
        <title> {formattedDataPresentation.name} - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        />
      </Head>
      <Navbar />
      <main>
        <Presentation
          presentation={formattedDataPresentation.objective}
          name={formattedDataPresentation.name}
          company={formattedDataPresentation.company}
          job={formattedDataPresentation.job}
          description={formattedDataPresentation.description}
          dataCards={formattedDataCards}
        />
        <Form db={db} />
        <div>
          <Map />
        </div>
      </main>
      <Footer />
    </>
  );
}
export const getServerSideProps: GetServerSideProps = async () => {
  const querySnapshotPresentation = await getDocs(
    collection(db, "presentation")
  );
  const dataPresentation = querySnapshotPresentation.docs.map((doc) =>
    doc.data()
  );
  const querySnapshotCards = await getDocs(collection(db, "cards"));
  const dataCards = querySnapshotCards.docs.map((doc) => doc.data());
  const formattedDataPresentation = dataPresentation[0];
  const formattedDataCards = dataCards[0];
  return { props: { formattedDataPresentation, formattedDataCards } };
};
